---
engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
           mass_threshold: 25
  eslint:
    enabled: true
  rubocop:
    enabled: true
  brakeman:
    enabled: true
    # --ignore-model-output
  csslint:
    enabled: true
  coffeelint:
    enabled: true

ratings:
  paths:
  - "**.rb"
  - "**.css"
  - "**.coffee"

exclude_paths:
- config/
- bin/
