---
engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
        ruby:
           mass_threshold: 25
  eslint:
    enabled: true
    no-unused-expressions:
      enabled: false
  rubocop:
    enabled: true
  brakeman:
    enabled: true
    checks:
      cross_site_scripting:
        enabled: false
  csslint:
    enabled: true
  coffeelint:
    enabled: true

ratings:
  paths:
  - "**.rb"
  - "**.css"
  - "**.coffee"

exclude_paths:
- config/
- bin/
