language: ruby

rvm:
  2.3.1

before script:
  - psql -c 'create database chess-app_test;' -U postgres

# Configure to use Code Climate
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: ENV["code_climate_token"]
# regular test configuration
after_success:
  - bundle exec codeclimate-test-reporter